* Library Information
 Readme.org --- Extensions to look-mode for dired buffers

 - Filename :: [[file:look-dired.el][look-dired.el]]
 - Description :: Extensions to look-mode for dired buffers
 - Author :: Joe Bloggs <vapniks@yahoo.com>
 - Maintainer :: Joe Bloggs <vapniks@yahoo.com>
Copyleft (Ↄ) 2013, Joe Bloggs, all rites reversed.
 - Created :: 2013-05-11 20:39:19
 - Version :: 0.1
 - Last-Updated :: 2013-05-11 20:39:19
 -           By :: Joe Bloggs
 - URL :: https://github.com/vapniks/look-dired
 - Keywords :: convenience
 - Compatibility :: GNU Emacs 24.3.1
 - Package-Requires :: ((look-mode 1.0))

* Possible Dependencies

look-mode 

* Commentary
Bitcoin donations gratefully accepted: 1ArFina3Mi8UDghjarGqATeBgXRDWrsmzo

This library provides extra commands for [[http://www.emacswiki.org/emacs/LookMode][look-mode]] (see below).
In addition if you mark some files in a dired buffer and then run look-at-file (or press M-l), 
all of the marked files will be visited in the *look* buffer.
** New commands
- look-dired-do-rename                  : Rename current looked file, to location given by TARGET.
- look-dired-unmark-looked-files        : Unmark all the files in `look-buffer' in the corresponding dired-mode buffer.
- look-dired-mark-looked-files          : Mark all the files in `look-buffer' in the corresponding dired-mode buffer.
- look-dired-mark-current-looked-file   : Mark `look-current-file' in the corresponding dired-mode buffer.
- look-dired-unmark-current-looked-file : Unmark `look-current-file' in the corresponding dired-mode buffer.
- look-dired-run-associated-program     : Run program associated with currently looked at file.

* Installation

 - If you have [[http://www.marmalade-repo.org/][marmalade-repo.org]], this look-dired is part of the emacs packages you can install.  Just type M-x package-install look-dired marmalade 
 - Otherwise download the library from here Lisp:look-dired, and put it in a directory in the emacs load path, like ~/.emacs.d
 - Add (require 'look-dired) in your ~/.emacs file
